// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserImpl _$$UserImplFromJson(Map<String, dynamic> json) => _$UserImpl(
      fullName: json['full_name'] as String?,
      nameParent: json['name_parent'] as String?,
      address: json['address'] as String?,
      email: json['email'] as String?,
      phoneNumber: json['phone_number'] as String?,
      emailParent: json['email_parent'] as String?,
      imageParent: json['img_parent'] as String?,
      key: json['key'] as String?,
      afiliasi: json['afiliasi'],
      omset: (json['omset'] as num?)?.toInt(),
      saldo: json['saldo'] as String?,
      subdomain: json['subdomain'] as String?,
      point: json['point'] as String?,
      transaksi: (json['transaksi'] as num?)?.toInt(),
      order: (json['order'] as num?)?.toInt(),
      type: json['type'] as String?,
      systemPoint: json['system_point'],
      img: json['img'] as String?,
      signup: json['signup'],
      nameStore: json['name_store'] as String?,
      idStaff: json['id_staff'] as String?,
      level: json['level'] as String?,
      nis: json['nis'] as String?,
      ttl: json['ttl'] as String?,
      position: json['position'] as String?,
      date: json['date'] as String?,
      absensi: json['absensi'] as String?,
      tabungan: json['tabungan'] as String?,
      limit_harian: (json['limit_harian'] as num?)?.toInt(),
      menabung_terakhir: json['menabung_terakhir'] as String?,
      status_kartu: json['status_kartu'] as String?,
      uang_saku: json['uang_saku'] as String?,
      uang_loundry: json['uang_loundry'] as String?,
      uang_belanja: json['uang_belanja'] as String?,
      location: json['location'] as String?,
    );

Map<String, dynamic> _$$UserImplToJson(_$UserImpl instance) =>
    <String, dynamic>{
      'full_name': instance.fullName,
      'name_parent': instance.nameParent,
      'address': instance.address,
      'email': instance.email,
      'phone_number': instance.phoneNumber,
      'email_parent': instance.emailParent,
      'img_parent': instance.imageParent,
      'key': instance.key,
      'afiliasi': instance.afiliasi,
      'omset': instance.omset,
      'saldo': instance.saldo,
      'subdomain': instance.subdomain,
      'point': instance.point,
      'transaksi': instance.transaksi,
      'order': instance.order,
      'type': instance.type,
      'system_point': instance.systemPoint,
      'img': instance.img,
      'signup': instance.signup,
      'name_store': instance.nameStore,
      'id_staff': instance.idStaff,
      'level': instance.level,
      'nis': instance.nis,
      'ttl': instance.ttl,
      'position': instance.position,
      'date': instance.date,
      'absensi': instance.absensi,
      'tabungan': instance.tabungan,
      'limit_harian': instance.limit_harian,
      'menabung_terakhir': instance.menabung_terakhir,
      'status_kartu': instance.status_kartu,
      'uang_saku': instance.uang_saku,
      'uang_loundry': instance.uang_loundry,
      'uang_belanja': instance.uang_belanja,
      'location': instance.location,
    };
