// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'store.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$StoreImpl _$$StoreImplFromJson(Map<String, dynamic> json) => _$StoreImpl(
      idStore: json['id_store'] as String?,
      nameStore: json['name_store'] as String?,
      numberStore: json['number_store'] as String?,
      address: json['address'] as String?,
      email: json['email'] as String?,
      nohp: json['nohp'] as String?,
      tax: json['tax'] as String?,
      serviceCharge: json['service_charge'] as String?,
      saldo: json['saldo'] as String?,
      point: json['point'] as String?,
      order: json['order'] as String?,
      type: json['type'] as String?,
      omset: json['omset'],
      level: json['level'] as String?,
      position: json['position'] as String?,
      shift: json['shift'] as String?,
      initial: json['initial'],
      footer: json['footer'],
      photo: json['photo'] as String?,
      img: json['img'] as String?,
      nameStaff: json['name_staff'] as String?,
      attandence: (json['attandence'] as num?)?.toInt(),
      job: (json['job'] as num?)?.toInt(),
      today: json['today'] as String?,
      workhour: json['workhour'] as String?,
      timeattand: json['timeattand'] as String?,
      during: json['during'] as String?,
      late: json['late'] as String?,
      notif: json['notif'] as String?,
      notifpelanggaran: json['notifpelanggaran'] as String?,
      notifizin: json['notifizin'] as String?,
      notifizinsantri: json['notifizinsantri'] as String?,
      notifmudir: json['notifmudir'] as String?,
      notifmanager: json['notifmanager'] as String?,
      notifkeuangan: json['notifkeuangan'] as String?,
      notiflogistik: json['notiflogistik'] as String?,
      notifpermintaanobatmanager: json['notifpermintaanobatmanager'] as String?,
      notifukp: json['notifukp'] as String?,
      absen: json['absen'] as String?,
      guru: json['guru'] as String?,
      holiday: json['holiday'] as String?,
      notifinfo: json['notifinfo'] as String?,
      chat: json['chat'] as String?,
      kepengasuhan: json['kepengasuhan'] as String?,
      kependidikan: json['kependidikan'] as String?,
      kerumahtanggaan: json['kerumahtanggaan'] as String?,
      tahfidz: json['tahfidz'] as String?,
      kesehatan: json['kesehatan'] as String?,
      permohonan: json['permohonan'] as String?,
      keuangan: json['keuangan'] as String?,
      meeting: json['meeting'] as String?,
      unitusaha: json['unitusaha'] as String?,
    );

Map<String, dynamic> _$$StoreImplToJson(_$StoreImpl instance) =>
    <String, dynamic>{
      'id_store': instance.idStore,
      'name_store': instance.nameStore,
      'number_store': instance.numberStore,
      'address': instance.address,
      'email': instance.email,
      'nohp': instance.nohp,
      'tax': instance.tax,
      'service_charge': instance.serviceCharge,
      'saldo': instance.saldo,
      'point': instance.point,
      'order': instance.order,
      'type': instance.type,
      'omset': instance.omset,
      'level': instance.level,
      'position': instance.position,
      'shift': instance.shift,
      'initial': instance.initial,
      'footer': instance.footer,
      'photo': instance.photo,
      'img': instance.img,
      'name_staff': instance.nameStaff,
      'attandence': instance.attandence,
      'job': instance.job,
      'today': instance.today,
      'workhour': instance.workhour,
      'timeattand': instance.timeattand,
      'during': instance.during,
      'late': instance.late,
      'notif': instance.notif,
      'notifpelanggaran': instance.notifpelanggaran,
      'notifizin': instance.notifizin,
      'notifizinsantri': instance.notifizinsantri,
      'notifmudir': instance.notifmudir,
      'notifmanager': instance.notifmanager,
      'notifkeuangan': instance.notifkeuangan,
      'notiflogistik': instance.notiflogistik,
      'notifpermintaanobatmanager': instance.notifpermintaanobatmanager,
      'notifukp': instance.notifukp,
      'absen': instance.absen,
      'guru': instance.guru,
      'holiday': instance.holiday,
      'notifinfo': instance.notifinfo,
      'chat': instance.chat,
      'kepengasuhan': instance.kepengasuhan,
      'kependidikan': instance.kependidikan,
      'kerumahtanggaan': instance.kerumahtanggaan,
      'tahfidz': instance.tahfidz,
      'kesehatan': instance.kesehatan,
      'permohonan': instance.permohonan,
      'keuangan': instance.keuangan,
      'meeting': instance.meeting,
      'unitusaha': instance.unitusaha,
    };
