 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQF6-D46wjIkwPb4IW3aUsPg6Ggovb2lU',
    appId: '1:859044680272:web:3385a8eff140200d43f755',
    messagingSenderId: '859044680272',
    projectId: 'rabbaniiapps',
    authDomain: 'rabbaniiapps.firebaseapp.com',
    storageBucket: 'rabbaniiapps.appspot.com',
    measurementId: 'G-0Q5XCW176E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7EG9hMQQFQEURKkn_mq0yP6L5X0reoB0',
    appId: '1:859044680272:android:3d9263e8db9bc45843f755',
    messagingSenderId: '859044680272',
    projectId: 'rabbaniiapps',
    storageBucket: 'rabbaniiapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBos1Gh-XXrZaxHF-syAt0lDCALew184wI',
    appId: '1:859044680272:ios:9efb208e8b0ecc2243f755',
    messagingSenderId: '859044680272',
    projectId: 'rabbaniiapps',
    storageBucket: 'rabbaniiapps.appspot.com',
    iosBundleId: 'com.muslimdeveloper.rabbaaniiPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBos1Gh-XXrZaxHF-syAt0lDCALew184wI',
    appId: '1:859044680272:ios:9efb208e8b0ecc2243f755',
    messagingSenderId: '859044680272',
    projectId: 'rabbaniiapps',
    storageBucket: 'rabbaniiapps.appspot.com',
    iosBundleId: 'com.muslimdeveloper.rabbaaniiPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQF6-D46wjIkwPb4IW3aUsPg6Ggovb2lU',
    appId: '1:859044680272:web:5a35b16f5f42cbaa43f755',
    messagingSenderId: '859044680272',
    projectId: 'rabbaniiapps',
    authDomain: 'rabbaniiapps.firebaseapp.com',
    storageBucket: 'rabbaniiapps.appspot.com',
    measurementId: 'G-8Z3XK5JLG1',
  );
}